artifacts_config:
  artifacts_dir: artifacts

data_ingestion_config:
  dataset_download_url: https://github.com/vatsalm1611/data
  dataset_dir: dataset
  ingested_dir: ingested_data
  raw_data_dir: raw_data
  use_local_files: true



data_validation_config:
  clean_data_dir: clean_data
  serialized_objects_dir: serialized_objects
  books_csv_file: BX-Books.csv
  ratings_csv_file: BX-Book-Ratings.csv



data_transformation_config:
  transformed_data_dir: transformed_data



model_trainer_config:
  trained_model_dir: trained_model
  trained_model_name: model.pkl


recommendation_config:
  trained_model_path: artifacts/trained_model/model.pkl
  book_pivot_serialized_objects: artifacts/serialized_objects/book_pivot.pkl
  final_rating_serialized_objects: artifacts/serialized_objects/final_rating.pkl
  poster_api_url: https://covers.openlibrary.org/b/isbn/{}


